select_origin: directory
files_origin: "data"
nodes_origin: ""
links_origin: ""
nodes_online: ""
links_online: ""
images_origin: "./images/"
export_target: "./export/"
history: true
focus_max: 5
record_types:
  undefined:
    fill: "#858585"
    stroke: "#858585"
link_types:
  undefined:
    stroke: simple
    #color: "000000"
    color: "#e1e1e1"
references_as_nodes: false
references_type_label: references
graph_background_color: "#ffffff"
#graph_background_color: "#fef1da"
graph_highlight_color: "#ff6a6a"
graph_highlight_on_hover: true
graph_text_size: 10
graph_arrows: true
node_size_method: degree
node_size: 15
node_size_max: 20
node_size_min: 10
attraction_force: 600
attraction_distance_max: 350
attraction_vertical: 0
attraction_horizontal: 0
views: {}
record_metas: []
record_filters: []
generate_id: always
link_context: tooltip
hide_id_from_record_header: false
title: "préserver et diffuser le code source"
author: "Damien Belvèze"
description: ""
keywords: []
link_symbol: ""
csl: "apa.csl"
bibliography: "./references.bib"
csl_locale: ""
css_custom: ""
devtools: false
lang: fr
